import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Banner from "../components/banner/banner"
import NavBar from '../components/nav/navbar'
import SectionCards from '../components/card/section-cards'

export default function Home() {
  const disneyVideos = [
    {
      imgUrl: '/static/cover-1.jpg'
    }
  ]

  const travelVideos = [
    {
      imgUrl: '/static/cover-1.jpg'
    }
  ]

  const productivityVideos = [
    {
      imgUrl: '/static/cover-1.jpg'
    }
  ]

  const popularVideos = [
    {
      imgUrl: '/static/cover-1.jpg'
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="pxhanonxhumparat@gmail.com" />
      <Banner
        videoId="F4P6GeC6gcs"
        title="The Dark Knight Rises"
        subTitle="The legend ends July 20 experience it in IMAX"
        imgUrl="/static/cover-4.jpeg"
      />

        <div className={styles.sectionWrapper}>
          <SectionCards title='Disney' videos={disneyVideos} size='large' />
          <SectionCards title='Travel' videos={travelVideos} size='small' />
          <SectionCards title='Productivity' videos={productivityVideos} size='small' />
          <SectionCards title='Popular' videos={popularVideos} size='small' />
        </div>
      {/* <Card imgUrl='/static/cover-1.jpg' size='large' />
      <Card size='medium' />
      <Card imgUrl='/static/cover-1.jpg' size='small' /> */}
    </div>
  )
}
